// shelf-page.js v1.00 | THE SHELF BOT's generator (the Director's yes, 2026-09-29; doc 13 section 11): builds test/index.html,
// the device-test shelf page, from what test/ holds. The page logic is lifted verbatim from the studio's tools/snailcade.js
// v1.05, which now calls this file, so the tool and the bot can never write two different pages.
//   node .github/shelf/shelf-page.js     (from the snailcade repo root) writes test/index.html; prints the build count
// Run by .github/workflows/shelf-page.yml after every merge to main. The only writer of test/index.html: seats commit
// builds only. Plain node, no packages. The page carries its own version (PAGE); bump it only when the page changes.
'use strict';
const fs = require('fs'), path = require('path'), crypto = require('crypto');
const VERSION = 'v1.00';
const PAGE = 'v1.04';
const sha = (f) => crypto.createHash('sha256').update(fs.readFileSync(f)).digest('hex');
const esc = (s) => String(s).replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
const VRX = /-v(\d+(?:[._]\d+)*)\.html$/;   /* v1.03: -v1.62.html and -v1_62.html both read 1.62 */
const vparts = (f) => ((f.match(VRX) || [])[1] || '0').split(/[._]/).map(Number);   /* for sorting only */
const vlabel = (f) => 'v' + ((f.match(VRX) || [])[1] || '0').replace(/_/g, '.');   /* v1.05: the card keeps the name's digits */
const vcmp = (a, b) => { const x = vparts(a), y = vparts(b); for (let i = 0; i < Math.max(x.length, y.length); i++) { const d = (y[i] || 0) - (x[i] || 0); if (d) return d; } return a < b ? -1 : 1; };
const display = (slug) => slug.split('-').join(' ').toUpperCase();

/* every playable build on the shelf: test/<slug>/<file>.html, newest version first within a title */
function builds(shelf) {
  const T = path.join(shelf, 'test'), out = [];
  if (!fs.existsSync(T)) return out;
  for (const slug of fs.readdirSync(T).sort()) {
    const d = path.join(T, slug); if (!fs.statSync(d).isDirectory()) continue;
    const files = fs.readdirSync(d).filter((f) => f.endsWith('.html')).sort(vcmp);
    for (const f of files) out.push({ slug, file: f, rel: 'test/' + slug + '/' + f, abs: path.join(d, f) });
  }
  return out;
}

function page(list) {
  const titles = [...new Set(list.map((b) => b.slug))];
  const kb = (f) => Math.round(fs.statSync(f).size / 1024) + ' KB';
  const sections = titles.map((slug) => {
    const rows = list.filter((b) => b.slug === slug).map((b, i) =>
      '      <a class="build" href="' + esc(b.slug + '/' + b.file) + '">\n' +
      '        <span class="ver">' + esc(vlabel(b.file)) + (i === 0 ? ' <b>LATEST</b>' : '') + '</span>\n' +
      '        <span class="file">' + esc(b.file) + '</span>\n' +
      '        <span class="meta">' + kb(b.abs) + ' | sha256 ' + sha(b.abs).slice(0, 12) + '</span>\n' +
      '      </a>').join('\n');
    return '    <section class="title" data-slug="' + esc(slug) + '">\n      <h2>' + esc(display(slug)) + '</h2>\n' + rows + '\n    </section>';
  }).join('\n');
  const n = list.length;
  return `<!DOCTYPE html>
<!-- SNAILCADE TEST SHELF ${PAGE} | GENERATED by tools/snailcade.js in the studio repo at test/index.html (the page's version is its own, not the tool's); never edit by hand. Rules: doc 13 section 11. -->
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
<meta name="robots" content="noindex, nofollow">
<title>SNAILCADE Test Shelf ${PAGE}</title>
<style>
  :root { --bg: #07070f; --panel: #10122a; --edge: #2c3bd6; --ink: #e8ebff; --dim: #8c93c9; --gold: #f4c43a; --red: #e2463c; }
  * { box-sizing: border-box; }
  html, body { margin: 0; background: var(--bg); color: var(--ink); }
  body { font: 16px/1.4 ui-monospace, SFMono-Regular, Menlo, Consolas, "Liberation Mono", monospace; padding: 16px 16px 72px; min-height: 100vh; overflow-x: hidden; }
  main { max-width: 640px; margin: 0 auto; }
  h1 { margin: 8px 0 4px; font-size: 28px; letter-spacing: 2px; color: var(--gold); text-shadow: 3px 3px 0 var(--red); }
  .sub { margin: 0 0 20px; color: var(--dim); font-size: 13px; }
  h2 { margin: 24px 0 8px; font-size: 18px; letter-spacing: 1px; color: var(--gold); }
  .build { display: block; margin: 0 0 10px; padding: 14px 16px; background: var(--panel); border: 2px solid var(--edge); border-radius: 6px; color: var(--ink); text-decoration: none; }
  .build:active, .build:hover { border-color: var(--gold); }
  .ver { display: block; font-size: 20px; }
  .ver b { margin-left: 8px; padding: 1px 6px; font-size: 12px; color: var(--bg); background: var(--gold); border-radius: 3px; vertical-align: middle; }
  .file { display: block; margin-top: 4px; font-size: 13px; color: var(--dim); overflow-wrap: anywhere; }
  .meta { display: block; margin-top: 2px; font-size: 12px; color: var(--dim); overflow-wrap: anywhere; }
  .empty { color: var(--dim); }
  #badge { position: fixed; right: 12px; bottom: 12px; padding: 6px 10px; font-size: 12px; color: var(--bg); background: var(--gold); border-radius: 4px; z-index: 9; }
</style>
</head>
<body>
  <main>
    <h1>SNAILCADE</h1>
    <p class="sub">Snail Attack Studios test shelf. ${n} playable build${n === 1 ? '' : 's'}. Tap a build to play it.</p>
${n ? sections : '    <p class="empty">No builds on the shelf yet.</p>'}
  </main>
  <div id="badge">TEST SHELF ${PAGE} | ${n} build${n === 1 ? '' : 's'}</div>
</body>
</html>
`;
}

function write(shelf) {
  const list = builds(shelf), html = page(list);
  fs.mkdirSync(path.join(shelf, 'test'), { recursive: true });
  fs.writeFileSync(path.join(shelf, 'test', 'index.html'), html);
  return list.length;
}

module.exports = { VERSION, PAGE, VRX, vparts, vlabel, vcmp, builds, page, write };
if (require.main === module) {
  const shelf = path.resolve(__dirname, '..', '..');
  const n = write(shelf);
  console.log('SHELF PAGE (generator ' + VERSION + ', page ' + PAGE + '): test/index.html, ' + n + ' build' + (n === 1 ? '' : 's') + ' listed');
}
